name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: phpcs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install PHP and PHP Code Sniffer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: phpcs

      - name: Check code quality
        run: phpcs
