name: Code Quality

on:
  push:
  pull_request:

jobs:
  php:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Cancel previous incomplete runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout changes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install PHP and PHP Code Sniffer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: phpcs

      - name: Check code quality
        run: phpcs
