name: Tests

on:
  push:
  pull_request:

jobs:
  phpUnit:
    strategy:
      max-parallel: 3
      matrix:
        operatingSystem: [ubuntu-latest]
        phpVersion: ['8.0', '8.1', '8.2']
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    name: ${{ matrix.operatingSystem }} / PHP ${{ matrix.phpVersion }}
    steps:
      - name: Cancel previous incomplete runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersion }}

      - name: Setup dependency cache
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Run Tests
        run: ./vendor/bin/phpunit
