name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: phpunit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpUnit:
    strategy:
      max-parallel: 6
      matrix:
        phpVersion: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
      fail-fast: false
    runs-on: ubuntu-latest
    name: PHPUnit / PHP ${{ matrix.phpVersion }}
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersion }}

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Run Tests
        run: ./vendor/bin/phpunit
  phpStan:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Run Analysis
        run: ./vendor/bin/phpstan analyze
